FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 1.0

# ITAS Stock Management 1.0

<br />
<strong>Release notes</strong> (XX<sup>th</sup> July 2022.)

## New Endpoints

<ul>
<li>Production Schedular <b>Stock Intake Pile</b>: Pile Stock Intake Update,<a href="/#reference/production-schedular/pile-stock-intake"> Link</a></li>
<li>Production Schedular <b>Stock Intake Non Pile</b>: Non Pile Stock Intake Create,<a href="/#reference/production-schedular/non-pile-stock-intake"> Link</a></li>
<li>Production Schedular <b>Intake Reverse</b>: Reverse Intake,<a href="/#reference/production-schedular/intake-reverse"> Link</a></li>
</ul>

## AccessToken [/]
Model Header containing AccessToken

+ Model 
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

# Group Production Schedular
Processes relating to the Production Scheduling and related endpoints.

## Stock Intake Pile [/Production/{TradingEntityId}/Schedular/StockIntakePile/{ContractId}]
`PUT` Pile Stock Intake update and create split if quantity is less than call off quantity.

### Pile Stock Intake Update [PUT]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|Called Off Purchase Contract|Required|
|StockTankId|Stock Tank ID|`string`|11|Tank in Contract Terminal|Required|
|Quantity|Quantity|`decimal`||Not Exceed Call Off Qty|Required|
|IntakeDate|Intake Date|`datetime`||Defaults to today||

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`||||
|IsSplit|Is Split|`boolean`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ContractId (required, string, `P00001.001`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (PileStockIntake)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (ContractSplitResponseTrue)
        + Response (201 CreateResponse)

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (ContractSplitResponseFalse)
        + Response (200 UpdateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Stock Intake Non Pile [/Production/{TradingEntityId}/Schedular/StockIntakeNonPile]
`POST` Non Pile Stock Intake, Creates Contract and Intake record per lot. Split created if quantity is less than call off quantity.

### Non Pile Stock Intake Create [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|Called Off Purchase Contract|Required|
|Quantity|Quantity|`decimal`||Not Exceed Call Off Qty|Required|
|NumberOfLots|Number of Lots|`number`||Number of Warehouse Records to Create|Required|
|WarehouseCode|Warhouse Code|`string`|10|Warhouse in Contract Terminal||
|Units|Units|`decimal`||In Contract Packing Units||
|IntakeDate|Intake Date|`datetime`||Defaults to today||
|WarehouseEntries|see <b><a href="/#reference/data-object-definitions/warehouse-entry/warehouse-entry">Warehouse Entries</a></b> object|[array] of `object`||Entry Per Lot. Entries must add up to Quantity and Units received|Required|


<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`||||
|IsSplit|Is Split|`boolean`||||
|WarehouseRecords|see <b><a href="/#reference/data-object-definitions/warehouse-record/warehouse-record">Warehouse Record</a></b> object|[array] of `object`||||


+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity. 

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (NonPileStockIntake)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (NonPileStockIntakeResponse)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Intake Reverse [/Production/{TradingEntityId}/Schedular/IntakeReverse/{ContractId}]
`PUT` Reverses Intake by deleting contract and adding quantity back to header contract

### Reverse Intake [PUT]

<strong>URI Parameters</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|Taken in Contract|Required|

<hr />

<strong>Body Parameters</strong>

None.


+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ContractId (required, string, `P00001.001`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body 
    
            {
                none
            }

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ContractId: P00001.000 (string)
        + Response (200 UpdateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Maintain QA  [/Production/{TradingEntityId}/Schedular/MaintainQA/{ContractId}]
`PUT` Maintain the Contracts Quality Approved Code
### Update Quality Approved [PUT]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|Stock Item|Required|
|QACode|Quality Approved Code|`string`|1||Required|

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`||||


+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ContractId (required, string, `P00001.001`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (QualityApproved)

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ContractId: P00001.001 (string)
        + Response (200 UpdateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Move Stock Within Terminal  [/Production/{TradingEntityId}/Schedular/MaintainQA/{ContractId}]
`PUT` Move Stock Within Terminal, Create split if quantity to move is less than stock quantity.
### Move Within Terminal Update [PUT]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|Stock Item|Required|
|Quantity|Quantity|`number`||May not Exceed Stock Quantity|Required|
|Units|Units|`decimal`||Number of Units to Move|Required|
|WarehouseCode|Warehouse Code|`string`|10|Warehouse in Terminal|Required|
|ShedCode|Shed Code|`string`|8|Shed in Warehouse||
|WipAccountCode|WIP Account Code|`string`|11|Nominated WIP||

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`||||
|IsSplit|Is Split|`boolean`||||


+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ContractId (required, string, `P00001.001`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (MoveWithinTerminal)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (ContractSplitResponseTrue)
        + Response (201 CreateResponse)

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (ContractSplitResponseFalse)
        + Response (200 UpdateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)



# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Not that these endpoints are not accessable and only here for reference purposes.

## Warehouse Entry [/WarehouseEntry]
A multipurpose object used by several endpoints. 

### Warehouse Entry[GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Quantity|Quantity|`decimal`|||Required|
|Units|Units|`decimal`||||
|ShedCode|Shed Code|`string`|8|Shed in the Warehouse||
|Container|Container|`string`|15|||
|DateOfManufacture|Date Of Manufacture|`datetime`||||
|CypherNumber|Cypher Number|`number`||||
|UnitNumber|Unit Number|`number`||||
|FactoryNumber|Factory Number|`number`||||
|DamagedMissingBags|Damaged or Missing Bags|`number`||Creates Weight Loss split on Purchase Contract||


+ Response 200 (application/json; charset=utf-8)
+ Attributes (WarehouseEntry)

## Warehouse Record [/WarehouseRecord]
A multipurpose object used by several endpoints. 

### Warehouse Record[GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`||||
|ReleaseId|Release ID|`number`||||


+ Response 200 (application/json; charset=utf-8)
+ Attributes (WarehouseRecord)


# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 UpdateResponse (object)
+ Value: Updated (string)

## 200 DeletedResponse (object)
+ Value: Deleted (string)

## 200 AuthoriseResponse (object)
+ Value: Authorised (string)

## 201 CreateResponse (object)
+ Value: Created (string)

## 201 CreateMessages (object)
+ Messages (array [201 ErrorMessageDetail])

## 201 ErrorMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - LEG : {fieldName} has a {fieldName} of {value}.` (string)

## 201 CreateBllMessages (object)
+ Messages (array [201 ErrorBllMessageDetail])

## 201 ErrorBllMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)


## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5074 - API : The value sent in the querystring variable {Property} is not allowed.` (string)


## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)


## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)


## 404 Response (object)
+ Response
    + Value: 404 Not Found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5068 - Data : No records found.` (string)


## 405 Response (object)
+ Response
    + Value: 405 Method Not Allowed (string)
+ Messages (array[405 MethodNotAllowedMessage])

## 405 MethodNotAllowedMessage (object)
+ Severity: Error (string)
+ Message: `API5077 - API : That method is not supported, please check the ITAS API documentation.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg 

## ContractSplitResponseFalse (object)
+ ContractId: P00001.001 (string)
+ IsSplit: false (boolean)

## ContractSplitResponseTrue (object)
+ ContractId: P00001.002 (string)
+ IsSplit: true (boolean)

## MoveWithinTerminal (object)
+ ContractId: P00001.001 (required, string)
+ Quantity: 5 (required, number)
+ Units: 50 (required, number)
+ WarehouseCode: SISWHRS.P (required, string)
+ ShedCode: W1 (string)
+ WipAccountCode: WIPACC.000 (string)


## NonPileStockIntake (object)
+ ContractId: P00001.001 (required, string)
+ Quantity: 100 (required, number)
+ NumberOfLots: 1 (required, number)
+ WarehouseCode: SISWHRS.P (string)
+ Units: 1000 (number)
+ IntakeDate: `2022-06-22T00:00:00Z` (string)
+ WarehouseEntries (array [WarehouseEntry])

## NonPileStockIntakeResponse (object)
+ ContractId: P00001.002 (string)
+ IsSplit: true (boolean)
+ WarehouseRecords (array [WarehouseRecord])

## PileStockIntake (object)
+ ContractId: P00001.001 (required, string)
+ StockTankId: SISSILO.000 (required, string)
+ Quantity: 1000 (required, number)
+ IntakeDate: `2022-06-22T00:00:00Z` (string)

## QualityApproved (object)
+ ContractId: P00001.001 (required, string)
+ QACode: A (required, string)

## WarehouseEntry (object)
+ Quantity: 100 (required, number)
+ Units: 1000 (number)
+ ShedCode: W1 (string)
+ Container: UNIT7 (string)
+ DateOfManufacture: `2022-06-22T00:00:00Z` (string)
+ CypherNumber: 100 (number)
+ UnitNumber: 202 (number)
+ FactoryNumber: 201 (number)
+ DamagedMissingBags: 2 (number)

## WarehouseRecord (object)
+ ContractId: 800002.000 (string)
+ ReleaseId: 500 (number)
