FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 2.2.1

# ITAS API 2.2.1


This additional release to <a href="">`ITAS API 2.2`</a> includes changes to endpoints originally created in <a href="">`ITAS API 2.1`</a>. The affected endpoints have been higlighted as `UPDATED` iinline below. For full documentation of the changes please see the document <a href="/">`Updates to ITAS API between v2.2 and v2.2.1.docx`</a>.  

## AccessToken [/]
Model Header containing AccessToken

+ Model 
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

# Group Client Reference Data
Codes relating to Client Ledger and related endpoints.

## ClientAccount List [/ReferenceData/{TradingEntityId}/ClientLedger/ClientAccount/{Property}/{PropertyValue}]

### List ClientAccounts [GET]
`UPDATED`: this end point's URI is now singular, and some 200 response fields nave been added.
+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + Status
            + CanBeBuyer
            + CanBeSeller 
            + CanBeAgent
            + CanBeShipper
            + CanBeDerivativeClient 
            + CanBeDerivativeBroker 
            + EDICode: extABCDEF
    + PropertyValue (optional, string, `O`) ... required if property specified

+ Response 200 (application/json)
    + Attributes (ClientAccount List)
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

## ClientAccount [/ReferenceData/{TradingEntityId}/ClientLedger/ClientAccount/{ClientAccountId}]

### Read ClientAccount [GET]
`UPDATED`: this end point's URI is now singular, and some 200 response fields nave been added.
+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ClientAccountId (required, string, `ABCDEF.P`) 

+ Response 200 (application/json)
    + Attributes (ClientAccount)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

### Create ClientAccount [POST]
`UPDATED`: this end point's URI is now singular and some request objects have been flattened.
Create new Client Account
+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (ClientAccount CreateUpdate)

+ Parameters
    + TradingEntityId (required, string) ... identify specific trading entity
    + ClientAccountId (required, string) ... code for client account to create

+ Response 200 (application/json)
    + Attributes (200 CreateResponse)
    
+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)

### Update ClientAccount [PUT]
`UPDATED`: this end point's URI is now singular and some request objects have been flattened.<br/>
For Update requests the field `ClientAccountId` cannot be changed.
+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (ClientAccount CreateUpdate)

+ Parameters
    + TradingEntityId (required, string) ... identify specific trading entity
    + ClientAccountId (required, string) ... code for client account to create

+ Response 200 (application/json)
    + Attributes (201 UpdateResponse)
    
+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)


## ClientType List [/ReferenceData/{TradingEntityId}/ClientLedger/ClientType/{Property}/{PropertyValue}]
### List ClientTypes [GET]
User-defined list of codes used for classification purposes on Client Account profile.
+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + ClientTypeId
    + PropertyValue (optional, string, `H`) ... required if property specified 

+ Response 200 (application/json)
    + Attributes (array [ClientType List])
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)


# Group Nominal Reference Data
Codes relating to Nominal Ledger and related endpoints.

## Department List [/ReferenceData/{TradingEntityId}/NominalLedger/Department/{Property}/{PropertyValue}]
List all Departments in a given Trading Entity
### List Departments [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|DepartmentId|cmy102_dept|`string`|4||Unique Key|
|DepartmentDescription|cmy102_descr|`string`|30|||
|NominalCategoryCode|cmy102_category|`string`|2||must exist in gf_boec|
|CountryCode|cmy102_ctry|`string`|3||must exist in xx_cmy50|
|EDICode|cmy102_altcode|`string`|15|||
|Status|cmy102_inactive|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + DepartmentId
            + Status
            + EDICode
    + PropertyValue (optional, string, `O`) ... required if property specified


+ Response 200 (application/json)
    + Attributes (array[Department List])
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)


## Department [/ReferenceData/{TradingEntityId}/NominalLedger/Department/{DepartmentId}]
Details of a specific Department 

### Read Department [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|DepartmentId|cmy102_dept|`string`|4||Unique Key|
|DepartmentDescription|cmy102_descr|`string`|30|||
|NominalCategory||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/nominal-reference-data/nominalcategories-list">Nominal Category List</a> endpoint||
|CountryCode||`object`||see <a href="http://docs.itasapiv2r1.apiary.io/#reference/global-reference-data/countries-list">Countries List</a> endpoint||
|EDICode|cmy102_altcode|`string`|15|||
|Status|cmy102_inactive|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId (required, string, `AB`) ...  specific trading entity
    + DepartmentId (required, string, `5100`) ...  property department id 

+ Response 200 (application/json)
    + Attributes (Department)

+ Response 404 (application/json)
    + Attributes (404 Response)

## NominalAccount List [/ReferenceData/{TradingEntityId}/NominalLedger/NominalAccount/{Property}/{PropertyValue}]
Nominal (General) Ledger Account profile

### List NominalAccounts [GET]

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|NominalAccountId|nhr20_acc|`string`|9|||
|MainGroupingDescription|nhr20_titdescr|`string`|40|||
|DetailDescription|nhr20_detdescr|`string`|40|||
|BankAccount|nhr20_bankacc|`number`||||
|PrivilegeLevel|nhr20_priv|`string`|1|||
|EDICode|nhr20_altcode|`string`|30|||
|Status|nhr20_status|`string`|1|||


+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId (required, string, `AB`) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + NominalAccountId
            + BankAccount
            + EDICode
            + Status 
    + PropertyValue (optional, string, `AF`) ... required if property specified


+ Response 200 (application/json)
    + Attributes (array[NominalAccount])

+ Response 404 (application/json)
    + Attributes (404 Response)

## NominalAccount [/ReferenceData/{TradingEntityId}/NominalLedger/NominalAccount/{NominalAccountId}]
### Read NominalAccount [GET]
+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + NominalAccountId (required, string, `1234.5678`) 


+ Response 200 (application/json)
    + Attributes (NominalAccount)

+ Response 404 (application/json)
    + Attributes (404 Response)
    
### Update NominalAccount [PUT]
+ Response 200 (application/json)

## NominalCategory List [/ReferenceData/{TradingEntityId}/NominalLedger/NominalCategory/{Property}/{PropertyValue}]
Retrieve a list of Nominal categories for a specific Trading Entity.
### List NominalCategories [GET]
NEW - todo: description 

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|NominalCategoryId|cmy50_category|`string`|2||Unique Key |
|NominalCategoryDescription|cmy50_descr|`string`|50|||
|NominalGroup|cmy50_group|`string`|15|||


+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId (required, string, `AB`) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + NominalCategoryId
    + PropertyValue (optional, string, `AF`) ... required if property specified


+ Response 200 (application/json)
    + Attributes (array[NominalCatagory])

+ Response 404 (application/json)
    + Attributes (404 Response)

# Group Global Reference Data
Global (system-wide) codes 

## Country List [/ReferenceData/Global/Country/{Property}/{PropertyValue}]
See documentation in Apiary V2.1 for full details: http://docs.itasapiv2r1.apiary.io/#reference/global-reference-data/countries-list/list-countries
### List Countries [GET]
+ Response 200 (application/json)

## Currency List [/ReferenceData/Global/Currency/{Property}/{PropertyValue}]
See documentation in Apiary V2.1 for full details: http://docs.itasapiv2r1.apiary.io/#reference/global-reference-data/currencies-list/list-currencies
### List Currencies [GET]
+ Response 200 (application/json)


# Group Physicals Reference Data
Codes relating to Physicals Trading and related endpoints

## Commodity List [/ReferenceData/{TradingEntityId}/Physicals/Commodity/{Property}/{PropertyValue}]
### List Commodities [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|CommodityCodePart1|cmy03_commod|`string`|3|||
|CommodityCodePart2|cmy03_origin|`string`|6|||
|CommodityCodePart3|cmy03_grade|`string`|6|||
|CommodityCodePart4|cmy03_code4|`string`|6|||
|CommodityCodePart5|cmy03_code5|`string`|6|||
|CommodityDescription|cmy03_descr|`string`|250|||
|DocumentText|cmy03_text|`string`|4000|||
|CommodityGroup|cmy03_groupcd|`string`|3|||
|CountryCode|cmy03_ctry|`string`|3|||
|EDICode|cmy03_cmynum|`string`|15|||
|Status|cmy03_inactive|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + CommodityCodePart1 (optional, string) 
            + CommodityCodePart2 (optional, string)
            + CommodityCodePart3 (optional, string)
            + CommodityCodePart4 (optional, string)
            + CommodityCodePart5 (optional, string)
            + CommodityGroup (optional, string)
            + EDICode (optional, string)
            + Status (optional, string)
    + PropertyValue (optional, string, `O`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[Commodity])
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)

## PackingType List [/ReferenceData/{TradingEntityId}/Physicals/PackingType/{Property}/{PropertyValue}]
### List PackingTypes [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|PackingTypeId|cmy23_packcode|`string`|4||Unique Key |
|PackingTypeDescription|cmy23_descr|`string`|70|||
|EDICode|master_edicode|`string`|50|||
|Status|cmy23_inactive|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + PackingTypeId (optional, string) 
            + EDICode (optional, string)
            + Status (optional, string)
    + PropertyValue (optional, string, `O`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[PackingType])
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)

## PaymentTerm List [/ReferenceData/{TradingEntityId}/Physicals/PaymentTerm/{Property}/{PropertyValue}]
http://docs.itasapiv2r1.apiary.io/#reference/physicals-reference-data/paymentterms-list/list-currencies
### List PaymentTerms [GET]
+ Response 200 (application/json)

## Port List [/ReferenceData/{TradingEntityId}/Physicals/Port/{Property}/{PropertyValue}]
http://docs.itasapiv2r1.apiary.io/#reference/physicals-reference-data/ports-list/list-currencies
### List Ports [GET]
+ Response 200 (application/json)

## Sample List [/ReferenceData/{TradingEntityId}/Physicals/Sample/{Property}/{PropertyValue}]
### List Samples [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|SampleId|cmy36_sample|`string`|4||Unique Key |
|SampleDescription|cmy36_descr|`string`|50|||
|DocumentText|cmy36_text|`string`|4000|||
|NoOfCopiesRequired|cmy36_copies|`number`||||


+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + SampleId (optional, string,) 
    + PropertyValue (optional, string, `abc123`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[Sample])

+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)

## ShippingStatus List [/ReferenceData/{TradingEntityId}/Physicals/ShippingStatus/{Property}/{PropertyValue}]
### List ShippingStatuses [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ShippingStatusId|cmy28_afi|`string`|2||Unique Key |
|ShippingStatusDescription|cmy28_descr|`string`|50|||

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + ShippingStatusId (optional, string,) 
    + PropertyValue (optional, string, `OR`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[ShippingStatus])

+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)

## Terminal List [/ReferenceData/{TradingEntityId}/Physicals/Terminal/{Property}/{PropertyValue}]
### List Terminals [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|TerminalId|cmy21_terminal|`string`|4|||
|TerminalDescription|cmy21_descr|`string`|50|||
|CountryCode|cmy21_ctry|`string`|3||must exist in gf_boec|


+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + TerminalId (optional, string) 
    + PropertyValue (optional, string, `O`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[Terminal])

+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)

## Vessel List [/ReferenceData/{TradingEntityId}/Physicals/Vessel/{Property}/{PropertyValue}]
http://docs.itasapiv2r1.apiary.io/#reference/physicals-reference-data/vessels-list/list-currencies
### List Vessels [GET]
+ Response 200 (application/json)

## Weight List [/ReferenceData/{TradingEntityId}/Physicals/Weight/{Property}/{PropertyValue}]
### List Weights [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|WeightId|cmy11_wtcode|`string`|4||Unique Key |
|WeightDescription|cmy11_descr|`string`|50|||
|DocumentText|cmy11_text|`string`|4000|||
|DecimalPlacesPresentation|cmy11_plc|`number`||||
|ConversionFactorToKilos|cmy11_conversion|`number`|24,17|||
|EDICode|cmy11_altcode|`string`|50|||
|Status|cmy11_inactive|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + WeightId (optional, string) 
            + EDICode (optional, string)
            + Status (optional, string)
    + PropertyValue (optional, string, `abc123`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (array[Weight])
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)

+ Response 404 (application/json)
    + Attributes (404 Response)


# Group WIP Reference Data
WIP Ledger related reference data

## StockUnit List [/RefrenceData/{TradingEntityId}/WipLedger/StockUnit/{Property}/{PropertyValue}]
### List StockUnits [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|StockUnitId|cna50_acc|`string`|11|||
|StockUnitDescription|cna50_descr|`string`|60|||
|TerminalCode|cna50_terminal|`string`|4||must exist in xx_cmy21|
|DepartmentCode|cna50_dept|`string`|4||must exist in xx_cmy102|
|CommodityCode|composite key delimited by double pipe &#124; &#124; |`string`|35||CompositeKey|
|NominalAccountCode|cna50_liqplacc|`string`|9||must exist in xx_nhr20|
|StockOwnerCode|cna50_owner|`string`|50||must exist in xx_chr20|
|ReleaseState|cna50_siemenrel|`number`||||
|CurrentStatus|cna50_siemenstatus|`number`||||
|PrivilegeLevel|cna50_priv|`number`|1||0-9|
|EDICode|cna50_c2cacc|`string`|9|||
|Status|cna50_status|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId: AB (required, string) ... identify specific trading entity
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + StockunitId (optional, string) 
            + TerminalCode (optional, string)
            + EdiCode (optional, string)
            + Status (optional, string)
    + PropertyValue (optional, string, `abc`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (StockUnitList)
    
+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

## StockUnit [/RefrenceData/{TradingEntityId}/WipLedger/StockUnit/{StockUnitId}]
### Read StockUnit [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|StockUnitId|cna50_acc|`string`|11|||
|StockUnitDescription|cna50_descr|`string`|60|||
|Terminal||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/terminals-list">Terminals List</a> endpoint||
|Department||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/nominal-reference-data/department/department-list">Department</a> endpoint||
|Commodity||`object`||see <a href"http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/commodities-list">Commodies List</a> endpoint||
|NominalAccount||`object`||Nominal Account delivered as an <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/accountheader">AccountHeader</a> object||
|StockOwner||`object`||Stock Owner delivered as an <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/accountheader">AccountHeader</a> object||
|ReleaseState|cna50_siemenrel|`number`||||
|CurrentStatus|cna50_siemenstatus|`number`||||
|PrivilegeLevel|cna50_priv|`number`|1||0-9|
|EDICode|cna50_c2cacc|`string`|9|||
|Status|cna50_status|`string`|1||`O` or `F`|

+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + StockUnitId (required, string, `5100.MEP`)

+ Response 200 (application/json)
    + Attributes (StockUnit)

+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)


# Group Inventory Management
Endpoints related to Stock Management, Order Scheduling & Order Processing 

## ExpedCallOff [/Inventory/{TradingEntityId}/Physicals/OrderScheduling/ExpedCallOffs/{ReleaseId}]
### Read ExpedCallOffs [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys01_releasenr|`number`||||
|ContractType|phys01_contype|`string`|1|||
|ContractDate|phys01_condate|`number`||DateTime||
|DeliveryDate|phys01_startper|`number`||DateTime||
|Department||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/nominal-reference-data/departments">Departments List</a> endpoint||
|Counterparty||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/read-expedcalloffss">Account Header</a> object||
|Memorandum|phys01_memo|`string`|4000|||
|InternalMemo|phys01_memo2|`string`|4000|||
|OrderStatus||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/shippingstatus-list">Shipping Status</a> endpoint||
|<strong>References</strong>|
|ContractReference|phys01_contract|`string`|10|||
|ClientReference|phys01_clref|`string`|40|||
|BuyerOrderNumber|phys01_buyerorderno|`string`|40|||
|BuyerSecondaryReference|phys01_buyersecref|`string`|40|||
|DeliveryClientOrderNumber|phys01_delorderno|`string`|40|||
|DeliveryClientSecondaryReference|phys01_delsecref|`string`|40|||
|<strong>GoodsDetails</strong>|
|Terminal||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/terminals-list">Terminals List</a> endpoint||
|Commodity||`object`||see <a href"http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/commodities-list">Commodies List</a> endpoint||
|Sample||`object`||see <a href"http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/sample-list">Samples List</a> endpoint||
|UnitOfMeasurement||`object`||see <a href"http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/weight-list">Weights List</a> endpoint||
|Quantity|phys01_conquan|`number`||||
|PackingType||`object`||see <a href"http://docs.itasapiv2r2.apiary.io/#reference/physicals-reference-data/packingtype-list">PackingType List</a> endpoint||
|<strong>TransportDetails</strong>|
|DeliveryClient||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/read-expedcalloffss">Account Header</a> object||
|Haulier||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/read-expedcalloffss">Account Header</a> object||
|Expeditor||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/data-object-definitions/read-expedcalloffss">Account Header</a> object||
|VehicleReference|phys01_vehicle|`string`|4|||
|VehicleRegistration|phys01_vehiclereg|`string`|50|||
|TrailerRegistration|phys01_trailerplate|`string`|50|||
|EarlyLoadAllowed|phys01_earlyload|`boolean`|1|||
|MaxLoadWeight|phys01_maxloadwt|`number`||||

+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, string, `abc123`)

+ Response 200 (application/json)
    + Attributes (ExpedCallOff)

+ Response 404 (application/json)
    + Attributes (404 Response)


## ExpedCallOff List [/Inventory/{TradingEntityId}/Physicals/OrderScheduling/ExpedCallOff/{Property}/{PropertyValue}]
### List ExpedCallOff [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys01_releasenr|`number`||||
|ContractType|phys01_contype|`string`|1|||
|ContractDate|phys01_condate|`number`||DateTime||
|DeliveryDate|phys01_startper|`number`||DateTime||
|DepartmentCode|phys01_dept|`string`|4|||
|CounterpartyCode|phys01_counterparty|`string`|10|||  
|Memorandum|phys01_memo|`string`|4000|||
|InternalMemo|phys01_memo2|`string`|4000|||
|OrderStatusCode|phys01_afi|`string`|2|||
|ContractReference|phys01_contract|`string`|10|||
|ClientReference|phys01_clref|`string`|40|||
|BuyerOrderNumber|phys01_buyerorderno|`string`|40|||
|BuyerSecondaryReference|phys01_buyersecref|`string`|40|||
|DeliveryClientOrderNumber|phys01_delorderno|`string`|40|||
|DeliveryClientSecondaryReference|phys01_delsecref|`string`|40|||
|TerminalCode|phys01_terminal|`string`|4|||
|CommodityFullCode|phys01_commod|`string`|3|||
|SampleCode|phys01_samplecode|`string`|4|||
|UnitOfMeasurementCode|phys01_wtcode|`string`|4|||
|Quantity|phys01_conquan|`number`||||
|PackingTypeCode|phys01_packcode|`string`|4|||
|DeliveryClientCode|phys01_delclient|`string`|10|||
|HaulierCode|phys01_haulageacc|`string`|10|||
|ExpeditorCode|phys01_expeditor|`string`|10|||
|VehicleReference|phys01_vehicle|`string`|4|||
|VehicleRegistration|phys01_vehiclereg|`string`|50|||
|TrailerRegistration|phys01_trailerplate|`string`|50|||
|EarlyLoadAllowed|phys01_earlyload|`boolean`|1|||
|MaxLoadWeight|phys01_maxloadwt|`number`||||

+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + ReleaseId 
            + DepartmentId
            + CounterpartyId
            + ContractReference
            + TerminaId
    + PropertyValue (optional, string, `abc123`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (ExpedCallOff List)

+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)


## DeliveryInOrder [/Inventory/{TradingEntityId}/Physicals/OrderScheduling/DeliveryInOrder/{ReleaseId}]
### Read DeliveryInOrder [GET]
NEW - todo: description, request properties, responses, data examples, accessToken

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys09_releasenr|`number`|0|||
|ExpedOrderDetails||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/inventory-management/expedcalloff">ExpedCallOff</a> endpoint||
|PumpingMemo|phys09_pumpmemo|`string`|250|||
|ProcessComplete|phys09_processed|`boolean`|1|||
|TargetStockUnitCode||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/wip-reference-data/stockunit">StockUnit</a> endpoint||


+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Response 200 (application/json)
    + Attributes (DeliveryInOrder)

+ Response 404 (application/json)
    + Attributes (404 Response)

## DeliveryOutOrder [/Inventory/{TradingEntityId}/Physicals/OrderScheduling/DeliveryOutOrder/{ReleaseId}]
### Read DeliveryOutOrder [GET]
NEW - todo: description, request properties, responses, data examples, accessToken

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys09_releasenr|`number`|0|||
|ExpedOrderDetails||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/inventory-management/expedcalloff">ExpedCallOff</a> endpoint||
|PumpingMemo|phys09_pumpmemo|`string`|250|||
|ProcessComplete|phys09_processed|`boolean`|1|||
|SourceStockUnitCode||`[object]`|array of StockLoading objects|see <a href="http://docs.itasapiv2r2.apiary.io/#reference/inventory-management/stockloading">StockLoading</a> endpoint||

+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Response 200 (application/json)
    + Attributes (DeliveryOutOrder)

+ Response 404 (application/json)
    + Attributes (404 Response)

## MarkOrderAsProcessed [/Inventory/{TradingEntityId}/Physicals/OrderProcessing/MarkOrderAsProcessed/{ReleaseId}]
### Update MarkOrderAsProcessed [GET]
NEW - todo: description, request properties, responses, data examples, accessToken
+ Response 200 (application/json)

## StockBatch [/Inventory/{TradingEntityId}/Physicals/StockManagement/StockBatch/{StockBatchId}]
### Read StockBatch [GET]
NEW - todo: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|StockBatchId|cna70_batchid|`string`|20|||
|StockUnitCode||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/wip-reference-data/stockunit">StockUnit</a> endpoint||
|BatchCreateDate|cna70_batchcreated|`string`|0|||
|BatchText|cna70_text|`string`|1000|||


+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + StockBatchId (required, string, `abc123`)

+ Response 200 (application/json)
    + Attributes (StockBatch)

+ Response 400 (application/json)
    + Attributes (400 Response)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

## StockBatch List [/Inventory/{TradingEntityId}/Physicals/StockManagement/StockBatch/{Property}/{PropertyValue}]
### List StockBatches [GET]
NEW - todo: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|StockBatchId|cna70_batchid|`string`|20|||
|StockUnitCode|cna70_acc|`string`|11|||
|BatchCreateDate|cna70_batchcreated|`string`|0|||
|BatchText|cna70_text|`string`|1000|||


+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + StockBatchId 
            + StockUnitCode
    + PropertyValue (optional, string, `abc123`) ... required if property specified.

+ Response 200 (application/json)
    + Attributes (StockBatch List)

+ Response 400 (application/json)
    + Attributes (400 BadPropertyResponse)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

## StockLoading [/Inventory/{TradingEntityId}/Physicals/OrderProcessing/StockLoading/{ReleaseId}]
### Read StockLoading [GET]
NEW - todo: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys10_releasenr|`number`|||Unique Key|
|SourceStockUnitCode||`object`|||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/wip-reference-data/stockunit">StockUnit</a> endpoint||
|Weight|phys10_qty|`number`||||

+ Request
    [AccessToken][]

+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Response 200 (application/json)
    + Attributes (array[StockLoading])
    
+ Response 400 (application/json)
    + Attributes (400 Response)
    
+ Response 404 (application/json)
    + Attributes (404 Response)

### Create StockLoading [POST]
NEW - todo: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys10_releasenr|`number`|||Unique Key|
|SourceStockUnitCode|phys10_tank|`string`|11||must exist in xx_cna50|
|Weight|phys10_qty|`number`||||

+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)
    
+ Request
    + Header
            
            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg
    + Attributes (array [ClientTypeList])

+ Response 200 (application/json)
    + Attributes (200 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)

### Update StockLoading [PUT]
Updat Stock Unit records. Please note that sending an update will remove any current records for the TradingEntity/ReleaseNr combination and replace them with records sent.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys10_releasenr|`number`|||Unique Key|
|SourceStockUnitCode|phys10_tank|`string`|11||must exist in xx_cna50|
|Weight|phys10_qty|`number`||||

+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

   + Attributes (StockLoadingFlat)

+ Response 200 (application/json)
    + Attributes (200 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)

## StockMovement [/Inventory/{TradingEntityId}/Physicals/OrderProcessing/StockMovement/{ReleaseId}]
### Read StockMovement [GET]
TODO: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys09_releasenr|`number`||||
|OrderAcknowledged|phys09_sent|`string`|1|||
|NetLoadedWeight|phys09_loaded|`number`||||
|NetPumpedWeight|phys09_pumped|`number`||||
|NetDeliveredWeight|phys09_delivered|`number`||||
|LoadedDate|phys09_loadeddate|`number`||||
|PumpedDate|phys09_pumpeddate|`number`||||
|TargetStockUnit||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/wip-reference-data/stockunit">StockUnit</a> endpoint||
|ArrivalDate|phys09_arrivaldate|`string`||||
|ArrivalMemo|phys09_arrivalmemo|`string`|250|||
|ArrivalWeight|phys09_arrivalweight|`number`||||
|LoadingStartDate|phys09_loadstartdate|`string`||||
|LoadingStartMemo|phys09_loadstartmemo|`string`|250|||
|LoadingEndDate|phys09_loadenddate|`string`||||
|LoadingPoint|phys09_loadendmemo|`string`|250|||
|FirstWeight|phys09_firstweight|`number`||||
|FirstWeightWeighbridgeId|phys09_firstweightwbid|`string`|10|||
|FirstWeightId|phys09_firstweightid|`string`|10|||
|SecondWeight|phys09_secondweight|`number`||||
|SecondWeightWeighbridgeId|phys09_secondweightwbid|`string`|10|||
|SecondWeightId|phys09_secondweightid|`string`|10|||

+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

   + Attributes (StockMovement)

+ Response 200 (application/json)
    + Attributes (StockMovement)

+ Response 404 (application/json)
    + Attributes (404 Response)

### Update StockMovement [PUT]
TODO: add description.

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys09_releasenr|`number`||||
|OrderAcknowledged|phys09_sent|`string`|1|||
|NetLoadedWeight|phys09_loaded|`number`||||
|NetPumpedWeight|phys09_pumped|`number`||||
|NetDeliveredWeight|phys09_delivered|`number`||||
|LoadedDate|phys09_loadeddate|`number`||||
|PumpedDate|phys09_pumpeddate|`number`||||
|TargetStockUnitCode|phys09_stock|`string`|11||must exist in xx_cna50|
|ArrivalDate|phys09_arrivaldate|`string`||||
|ArrivalMemo|phys09_arrivalmemo|`string`|250|||
|ArrivalWeight|phys09_arrivalweight|`number`||||
|LoadingStartDate|phys09_loadstartdate|`string`||||
|LoadingStartMemo|phys09_loadstartmemo|`string`|250|||
|LoadingEndDate|phys09_loadenddate|`string`||||
|LoadingPoint|phys09_loadendmemo|`string`|250|||
|FirstWeight|phys09_firstweight|`number`||||
|FirstWeightWeighbridgeId|phys09_firstweightwbid|`string`|10|||
|FirstWeightId|phys09_firstweightid|`string`|10|||
|SecondWeight|phys09_secondweight|`number`||||
|SecondWeightWeighbridgeId|phys09_secondweightwbid|`string`|10|||
|SecondWeightId|phys09_secondweightid|`string`|10|||


+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

   + Attributes (StockMovement Flat)

+ Response 200 (application/json)
    + Attributes (200 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)

## StockToStockOrder [/Inventory/{TradingEntityId}/Physicals/OrderScheduling/StockToStockOrder/{ReleaseId}]
### Read StockToStockOrder [GET]
NEW - todo: description

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|ReleaseId|phys09_releasenr|`number`||||
|TargetStockUnitCode||`object`||see <a href="http://docs.itasapiv2r2.apiary.io/#reference/wip-reference-data/stockunit">StockUnit</a> endpoint||
|Quantity|phys09_loaded|`number`||||
|TargetDate|phys09_targetdate|`string`||||
|PumpingMemo|phys09_pumpmemo|`string`|250|||
|ProcessComplete|phys09_processed|`boolean`|1|||
|SourceStockUnitCode||`[object]`|array of StockLoading objects|see <a href="http://docs.itasapiv2r2.apiary.io/#reference/inventory-management/stockloading">StockLoading</a> endpoint||


+ Parameters
    + TradingEntityId (required, string, `AB`) 
    + ReleaseId (required, number, `123`)

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

   + Attributes (StockMovement Flat)

+ Response 200 (application/json)
    + Attributes (200 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 Response)

+ Response 404 (application/json)
    + Attributes (404 Response)





# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Not that these endpoints are not accessable and only here for reference purposes.

## AccountHeader [/AccountHeader]
A multipurpose object used by several endpoints and with multiple source tables depending on context. The object described below is generic. 

### AccountHeader [GET]
|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|AccountType|A single letter denoting type|`string`|1|`C`, `N` or `K` are allowed values.||
|AccountId||`string`|11|||
|AccountDescription||`string`|200|||
|EDICode||`string`|50|||
|Status||`string`|1|||

+ Response 200 (application/json)
+ Attributes (AccountHeader)


# Data Structures

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg 

## AccountHeader (object)
+ AccountType: C | N | K (string)
+ AccountId: 00040444.P (string)
+ AccountDescription: Nigeria Trading Dept (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## AccountHeaderC (object)
+ AccountType: C (string)
+ AccountId: 00040444.P (string)
+ AccountDescription: Nigeria Trading Dept (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## AccountHeaderN (object)
+ AccountType: N (string)
+ AccountId: 0510.1000 (string)
+ AccountDescription: Computer Equipment | Cost (string)
+ EDICode: 1234 (string)
+ Status: O (string)

## AccountHeaderK (object)
+ AccountType: K    (string)
+ AccountId: 5100.MEP (string)
+ AccountDescription: Bauche Account Provisions (string)
+ EDICode: 1234 (string)
+ Status: O (string)

## 200 CreateResponse (object)
+ Response: Created (string)
+ Property: PropertyId (string)

## 201 UpdateResponse (object)
+ Response: Updated (string)
+ Property: PropertyId (string)

## 400 Response (object)
+ Response: 400 Bad Request (string)
+ Errors (array[400 ErrorMessageDetail])

## 400 BadPropertyResponse (object)
+ Response: 400 Bad Request (string)
+ Errors (array[400 BadPropertyErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ ErrorMessage: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)

## 400 BadPropertyErrorMessageDetail (object)
+ ErrorMessage: `API5068 - API : The value sent in the querystring variable {Property} is not allowed.` (string)

## 404 Response (object)
+ Response: 404 Object not found (string)
+ Errors (array[404 ErrorMessageDetail])

## 404 ErrorMessageDetail (object)
+ ErrorMessage: `API5067 - API : The value {TradingEntityId} sent as the TradingEntitiyId does not exist.` (string)

## ClientAccount (object)
+ ClientAccountId: ABCDEF.P (string) 
+ Title: ACME Trading Company (string)
+ ClientType (ClientType)
+ Status: O (string)
+ PrivilegeLevel: 9 (number) 
+ CanBeBuyer: true (boolean) 
+ CanBeSeller: true (boolean) 
+ CanBeAgent: false (boolean) 
+ CanBeShipper: false (boolean) 
+ CanBeDerivativeClient: false (boolean) 
+ CanBeDerivativeBroker: false (boolean) 
+ GlobalTraderProgramMember: true (boolean)
+ GroupAccountMember: false (boolean)
+ HeadOfFamilyAccountCode: HEAD.P (string)
+ EDICode: extABCDEF (string) 
+ ContactDetails (ContactDetails
+ ClientLimits - Client limits section
    + ClientDateLimitsApproved: `2015-12-01T00:00:00` (string)
    + ClientLimitsCurrency (Currency)
    + ClientPaymentLimit: 0 (number)
    + ClientMarketDefaultRiskLimit: 250000 (number)
    + ClientCommitmentLimit: 175000 (number)
+ FamilyLimits - Family limits section
    + FamilyDateLimitsApproved: `2016-02-20T00:00:00` (string)
    + FamilyLimitsCurrency (Currency)
    + FamilyPaymentLimit: 2000000 (number)
    + FamilyMarketDefaultRiskLimit: 3000000 (number)
    + FamilyCommitmentLimit: 2750000 (number)


## ClientAccount CreateUpdate (object)
+ ClientAccountId: ABCDEF.P (required, string) 
+ Title: ACME Trading Company (required, string)
+ ClientTypeCode: H (required, string)
+ Status: O (optional, string) ... Default value is `O` if not sent
+ PrivilegeLevel: 9 (number) ... Default value is `9` if not sent
+ CanBeBuyer: true (boolean) 
+ CanBeSeller: true (boolean) 
+ CanBeAgent: true (boolean) 
+ CanBeShipper: true (boolean) 
+ CanBeDerivativeClient: true (boolean) 
+ CanBeDerivativeBroker: true (boolean) 
+ GlobalTraderProgramMember: true (boolean)
+ GroupAccountMember: true (boolean)
+ HeadOfFamilyAccountCode: HEAD.P (string)
+ EDICode: extABCDEF (string) 
+ ContactDetails (ContactDetails CreateUpdate)
+ ClientLimits 
    + ClientDateLimitsApproved: `2015-12-01T00:00:00` (string)
    + ClientLimitsCurrencyCode: GBP (string)
    + ClientPaymentLimit: 0 (number)
    + ClientMarketDefaultRiskLimit: 250000 (number)
    + ClientCommitmentLimit: 175000 (number)
+ FamilyLimits
    + FamilyDateLimitsApproved: `2016-02-20T00:00:00` (string)
    + FamilyLimitsCurrencyCode: GBP (string)
    + FamilyPaymentLimit: 2000000 (number)
    + FamilyMarketDefaultRiskLimit: 3000000 (number)
    + FamilyCommitmentLimit: 2750000 (number)

## ClientAccount List (object)
+ ClientAccountId: ABCDEF.P (string) 
+ Title: `ACME Trading Company` (string)
+ ClientTypeCode: H (string)
+ Status: O (string)
+ PrivilegeLevel: 9 (number) 
+ CanBeBuyer: true (boolean) 
+ CanBeSeller: true (boolean) 
+ CanBeAgent: true (boolean) 
+ CanBeShipper: true (boolean) 
+ CanBeDerivativeClient: true (boolean) 
+ CanBeDerivativeBroker: true (boolean) 
+ EDICode: extABCDEF (string)

## ClientType (object)
+ ClientTypeId: H (string) 
+ ClientTypeDescription: House Account (string)

## ClientType List (object)
+ ClientTypeId: H (string) 
+ ClientTypeDescription: House Account (string)

## Commodity (object)
+ CommodityCodePart1: ORG (string)
+ CommodityCodePart2: `S1-45` (string)
+ CommodityCodePart3: FAIRT (string)
+ CommodityCodePart4: qwe (string)
+ CommodityCodePart5: ty (string)
+ CommodityDescription: Organic Golden Fairtrade Sugar (string)
+ DocumentText: Org Golden S1 45 ICUMSA (string)
+ CountryCode: MAL (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## ContactDetails (object)
+ AddressLine1: Address Line #1 (string)
+ AddressLine2: Address Line #2 (string) 
+ AddressLine3: Address Line #3 (string) 
+ AddressLine4: Address Line #4 (string) 
+ ZipCode: 01234567 (string) 
+ CountryCode (Country)
+ EmailAddress: info@abcdef.com (string)
+ PhoneNumber: 01234 567890 (string)
+ FaxNumber: 01234 567890 (string)

## ContactDetails CreateUpdate(object)
+ AddressLine1: Address Line #1 (string)
+ AddressLine2: Address Line #2 (string) 
+ AddressLine3: Address Line #3 (string) 
+ AddressLine4: Address Line #4 (string) 
+ ZipCode: 01234567 (string) 
+ CountryCode: GB (string) 
+ EmailAddress: info@abcdef.com (string)
+ PhoneNumber: 01234 567890 (string)
+ FaxNumber: 01234 567890 (string)

## Country (object)
+ CountryId: GB (string)
+ CountryDescription: Great Britain (string)

## Currency (object)
+ CurrencyId: GBP (string)
+ CurrencyDescription: British Pound (string)

## DeliveryInOrder (object)
+ ReleaseId: 12345 (number)
+ ExpedOrderDetails (ExpedCallOff)
+ PumpingMemo: memp text ges here (string)
+ ProcessComplete: 1 (boolean)
+ TargetStockUnitCode (StockUnit)

## DeliveryOutOrder (object)
+ ReleaseId: 12345 (number)
+ ExpedOrderDetails (ExpedCallOff)
+ PumpingMemo: memp text ges here (string)
+ ProcessComplete: 1 (boolean)
+ SourceStockUnitDetails (array [StockLoading])

## Department (object)
+ DepartmentId: 5100 (string)
+ DepartmentDescription: African Trading (string)
+ NominalCategory (NominalCatagory)
+ Country (Country)
+ EDICode: 1234 (string)
+ Status: F (string)

## Department List (object)
+ DepartmentId: 5100 (string)
+ DepartmentDescription: African Trading (string)
+ NominalCategoryId: AF (string)
+ CountryId: GB (string)
+ EDICode: 1234 (string)
+ Status: F (string)

## ExpedCallOff (object)
+ ReleaseId: 123 (number)
+ ContractType: S (string)
+ ContractDate: 20150930 (string)
+ DeliveryDate: 20150930 (string)
+ Department (Department)
+ Counterparty (AccountHeaderC)
+ Memorandum: notes field (string)
+ InternalMemo: notes field 2 (string)
+ OrderStatus (ShippingStatus)
+ References
    + ContractReference: AP13WG.000 (string)
    + ClientReference: abc123 (string)
    + BuyerOrderNumber: abc123 (string)
    + BuyerSecondaryReference: abc123 (string)
    + DeliveryClientOrderNumber: abc123 (string)
    + DeliveryClientSecondaryReference: abc123 (string)
+ GoodsDetails
    + Terminal (Terminal)
    + Commodity (Commodity)
    + Sample (Sample)
    + UnitOfMeasurement (Weight)
    + Quantity: 100 (number)
    + PackingType (PackingType)
+ TansportDetails
    + DeliveryClient (AccountHeaderC)
    + Haulier (AccountHeaderC)
    + Expeditor (AccountHeaderC)
    + VehicleReference: abc1 (string)
    + VehicleRegistration: YRS 386L (string)
    + TrailerRegistration: YRS 386L (string)
    + EarlyLoadAllowed: `true` (boolean)
    + MaxLoadWeight: 123 (number)

## ExpedCallOff List (object)
+ ReleaseId: 123 (number)
+ ContractType: S (string)
+ ContractDate: 20150930 (string)
+ DeliveryDate: 20150930 (string)
+ DepartmentCode: 5100 (string)
+ CounterpartyCode: 05990171.P (string)
+ Memorandum: notes field (string)
+ InternalMemo: notes field 2 (string)
+ OrderStatusCode: OR (string)
+ ContractReference: AP13WG.000 (string)
+ ClientReference: abc123 (string)
+ BuyerOrderNumber: abc123 (string)
+ BuyerSecondaryReference: abc123 (string)
+ DeliveryClientOrderNumber: abc123 (string)
+ DeliveryClientSecondaryReference: abc123 (string)
+ TerminalCode: ADEL (string)
+ CommodityCode: `ORG||S1-45||FAIRT||QWE||RTY` (string)
+ SampleCode: 123abc (string)
+ UnitOfMeasurementCode: GA (string)
+ Quantity: 100 (number)
+ PackingTypeCode: ABCD (string)
+ DeliveryClientCode: abc123 (string)
+ HaulierCode: abc123 (string)
+ ExpeditorCode: abc123 (string)
+ VehicleReference: abc1 (string)
+ VehicleRegistration: YRS 386L (string)
+ TrailerRegistration: YRS 386L (string)
+ EarlyLoadAllowed: `true` (boolean)
+ MaxLoadWeight: 123 (number)


## NominalAccount (object)
+ NominalAccountId: 1234.5678 (string) 
+ MainGroupingDescription: Direct Costs (string)
+ DetailDescription: Container Freight (string)
+ BankAccount: true (boolean) 
+ PrivilegeLevel: 5 (number) 
+ EDICode: ext12345678 (string) 
+ Status: O (string)

## NominalCatagory (object)
+ NominalCategoryId: AF (string)
+ NominalCatagoryDescription : Africa Tradeflow (string)
+ NominalGroup: AFGroup (string)

## PackingType (object)
+ PackingTypeId: 1050 (string)
+ PacingTypeDescription: In bags of 1050 kgs net (string)
+ EDICode: ext12345678 (string) 
+ Status: F (string)

## Sample (object)
+ SampleId: 123abc (string)
+ SampleDescription: Description of sample. (string)
+ DocumentText: Text to be used in the sameple document. (string)
+ NoOfCopiesRequired: 4 (number)

## ShippingStatus (object)
+ ShippingStatusId: OR (string)
+ ShippingStatusDescription: On Road (string)

## StockBatch (object)
+ StockBatchId: abc123 (string)
+ StockUnit (StockUnit)
+ BatchCreateDate: 100 (string)
+ BatchText: abc (string)

## StockBatch List (object)
+ StockBatchId: 123 (number)
+ StockUnitCode: xyz (string)
+ BatchCreateDate: 20160505 (number)
+ BatchText: abc (string)

## StockLoading (object)
+ ReleaseId: 123 (number)
+ SourceStockUnitCode (StockUnit)
+ Weight: 100 (string)

## StockLoadingFlat (object)
+ ReleaseId: 123 (number)
+ SourceStockUnitCode: xyz (string)
+ Weight: 100 (number)

## StockMovement (object)
+ ReleaseId: 100 (number)
+ OrderAcknowledged: N (string)
+ NetLoadedWeight: 10.00 (number)
+ NetPumpedWeight: 10.00 (number)
+ NetDeliveredWeight: 10.00 (number)
+ LoadedDate: 20160101 (string)
+ PumpedDate: 20160101 (string)
+ TargetStockId: 5100.MET (string)
+ ArrivalDetails
    + ArrivalDate: 20160101 (string)
    + ArrivalMemo: notes field (string)
    + ArrivalWeight: 10.00 (number)
+ LoadingStartDetails
    + LoadingStartDate: 20160101 (string)
    + LoadingStartMemo: notes field (string)
+ LoadingEndDetails
    + LoadingEndDate: 20160101 (string)
    + LoadingPoint: tring (string)
+ FirstWeightDetails
    + FirstWeight: 10.00 (number)
    + FirstWeightWeighbridgeId: abc123 (string)
    + FirstWeightId: abc123 (string)
+ SecondWeightDetails
    + SecondWeight: 10.00 (number)
    + SecondWeightWeighbridgeId: cde456 (string)
    + SecondWeightId: cde456 (string)

## StockMovement Flat (object)
+ ReleaseId: 100 (number)
+ OrderAcknowledged: N (string)
+ NetLoadedWeight: 10.00 (number)
+ NetPumpedWeight: 10.00 (number)
+ NetDeliveredWeight: 10.00 (number)
+ LoadedDate: 20160101 (string)
+ PumpedDate: 20160101 (string)
+ TargetStockUnitCode: 5100.MEP (string)
+ ArrivalDate: 20160101 (string)
+ ArrivalMemo: notes field (string)
+ ArrivalWeight: 10.00 (number)
+ LoadingStartDate: 20160101 (string)
+ LoadingStartMemo: notes field (string)
+ LoadingEndDate: 20160101 (string)
+ LoadingPoint: tring (string)
+ FirstWeight: 10.00 (number)
+ FirstWeightWeighbridgeId: abc123 (string)
+ FirstWeightId: abc123 (string)
+ SecondWeight: 10.00 (number)
+ SecondWeightWeighbridgeId: cde456 (string)
+ SecondWeightId: cde456 (string)

## StockToStockOrder (object)
+ ReleaseId: 12345 (number)
+ TargetStockUnitCode  (StockUnit)
+ Quantity: 123 (number)
+ TargetDate: 20165050 (string)
+ PumpingMemo: pumpingmemo text goes here. (string)
+ ProcessComplete: true (boolean)
+ SourceStockUnitDetails  (array[StockLoading])


## StockUnit (object)
+ StockUnitId: 5100.MEP (string)
+ StockUnitDescription: `MEPACCRUE - East Africa Dept` (string)
+ Terminal (Terminal)
+ Department (Department)
+ Commodity (Commodity)
+ NominalAccount (AccountHeaderN)
+ StockOwner (AccountHeaderC)
+ ReleaseState: abc (string)
+ CurrentStatus: def (string)
+ PrivilegeLevel: 5 (number)
+ EDICode: ext12345678 (string) 
+ Status: O (string)

## StockUnitList (object)
+ StockUnitId: 5100.MEP (string)
+ StockUnitDescription: `MEPACCRUE - East Africa Dept` (string)
+ TerminalCode: ADEL (string)
+ DepartmentCode: 5100 (string)
+ CommodityCode: `ORG||S1-45||FAIRT||QWE||RTY` (string)
+ NominalAccountCode: 00040444.P (string)
+ StockOwnerCode: 0500.0000 (string)
+ ReleaseState: 123 (number)
+ CurrentStatus: 456 (number)
+ PrivilegeLevel: 5 (number)
+ EDICode: ext12345678 (string) 
+ Status: O (string)

## Terminal (object)
+ TerminalId: ADEL (string)
+ TerminalDescription: `Santos-Santa Adelia` (string)
+ countryCode: BRA (string)

## Weight (object)
+ WeightId: GA (string)
+ WeightDescription: US Gallon (string)
+ DocumentText: Text for documenta.(string)
+ DecimalPlacesPresentation: 3 (number)
+ ConversionFactorToKilos: 2.7905 (number)
+ EdiCode: abc123 (string)
+ Status: F (string)